// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Image imports
declare module "*.png" {
  const value: string;
  export default value;
}

declare module "*.jpg" {
  const value: string;
  export default value;
}

declare module "*.svg" {
  const value: string;
  export default value;
}

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}
interface ChromeHistoryContext {
  detectHistoryPath: () => Promise<{
    success: boolean;
    defaultPath: string;
    profiles: string[];
    error?: string;
  }>;
  verifyPath: (path: string) => Promise<{
    success: boolean;
    error?: string;
    locked?: boolean;
  }>;
  readHistory: (path: string) => Promise<{
    success: boolean;
    data?: Array<{
      url: string;
      title: string;
      timestamp: string;
      visitCount: number;
      lastVisitTime: number;
    }>;
    error?: string;
  }>;
}
interface BraveHistoryContext {
  detectHistoryPath: () => Promise<{
    success: boolean;
    defaultPath: string;
    profiles: string[];
    error?: string;
  }>;
  verifyPath: (path: string) => Promise<{
    success: boolean;
    error?: string;
    locked?: boolean;
  }>;
  readHistory: (path: string) => Promise<{
    success: boolean;
    data?: Array<{
      url: string;
      title: string;
      timestamp: string;
      visitCount: number;
      lastVisitTime: number;
    }>;
    error?: string;
  }>;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  chromeHistory: ChromeHistoryContext;
  braveHistory: BraveHistoryContext;
}
